version: "3.9"

services:
  bot:
    build: .
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - USE_REDIS=true
    volumes:
      - ./:/app:delegated
      - ./database:/app/database
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:6.4.0
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: unless-stopped
    # ports:
    #   - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
